'use client';

import { useEffect, useRef, useState } from 'react';
import { Crosshair, MapPin, MapPinned } from 'lucide-react';
import { useSearchParams } from 'next/navigation';
import { request } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { useLocationStore } from '@/lib/location-store';
import { useToast } from '@/lib/toast';

const defaultCoords = { lat: 28.0229, lng: 73.3119 };
export default function AddressForm() {
  const { user } = useAuth(); const { addAddress, setLocation } = useLocationStore(); const { toast } = useToast();
  const searchParams = useSearchParams();
  const mapRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [coords, setCoords] = useState(defaultCoords); const [mapCenter, setMapCenter] = useState(defaultCoords);
  const [form, setForm] = useState({ name: '', mobile: '', address: '', houseNo: '', floor: '', landmark: '', city: '', type: 'home' });
  useEffect(() => { const openForm = () => setOpen(true); window.addEventListener('bb:add-address', openForm); if (searchParams.get('map') === '1') setOpen(true); return () => window.removeEventListener('bb:add-address', openForm); }, [searchParams]);
  useEffect(() => { if (user) setForm((current) => ({ ...current, name: current.name || user.name || '', mobile: current.mobile || user.mobile || '' })); }, [user]);
  const useMyLocation = () => { if (!navigator.geolocation) return toast('Location is not supported in this browser', 'error'); navigator.geolocation.getCurrentPosition((position) => { const next = { lat: position.coords.latitude, lng: position.coords.longitude }; setCoords(next); setMapCenter(next); toast('Pin moved to your current location'); }, () => toast('Could not get your location. Please allow location permission.', 'error'), { enableHighAccuracy: true, timeout: 10000 }); };
  const selectMapPoint = (event: React.PointerEvent<HTMLDivElement>) => { const rect = mapRef.current?.getBoundingClientRect(); if (!rect) return; const x = Math.min(1, Math.max(0, (event.clientX - rect.left) / rect.width)); const y = Math.min(1, Math.max(0, (event.clientY - rect.top) / rect.height)); setCoords({ lat: mapCenter.lat + (.5 - y) * .024, lng: mapCenter.lng + (x - .5) * .04 }); };
  const pinLeft = 50 + ((coords.lng - mapCenter.lng) / .04) * 100;
  const pinTop = 50 - ((coords.lat - mapCenter.lat) / .024) * 100;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!user) return window.dispatchEvent(new Event('bb:open-login')); if (!form.address.trim() || !form.city.trim()) return toast('Enter your area/address and city', 'error'); if (!/^\d{10}$/.test(form.mobile)) return toast('Enter a valid 10-digit mobile number', 'error'); setBusy(true); const result = await request<{ _id: string }>('/addresses', { method: 'POST', body: JSON.stringify({ name: form.name, mobile: form.mobile, address: form.address, house_No: form.houseNo, floor: form.floor ? Number(form.floor) : undefined, landmark: form.landmark, city: form.city, lat: coords.lat, lng: coords.lng, addressType: form.type, isDefault: true }) }); setBusy(false); if (!result.ok || !result.data) return toast(result.message, 'error'); window.localStorage.setItem('bb_selected_address', result.data._id); addAddress({ id: result.data._id, backendId: result.data._id, label: form.type === 'work' ? 'Work' : 'Home', city: form.city, area: form.address, fullAddress: [form.houseNo, form.address, form.landmark].filter(Boolean).join(', '), receiverName: form.name, phone: form.mobile }); setLocation(`${form.address}, ${form.city}`); toast('Delivery location saved'); setOpen(false); window.dispatchEvent(new Event('bb:address-saved')); }
  if (!open) return null;
  return <form className="address-form map-address-form" onSubmit={submit}><div className="address-form-title"><div><h3>Add delivery location</h3><p>Tap anywhere on the map to place the delivery pin, then add your address details.</p></div><button type="button" className="text-button" onClick={() => setOpen(false)}>Cancel</button></div><div className="map-picker" ref={mapRef} onPointerDown={selectMapPoint} onPointerMove={(event) => { if (event.buttons === 1) selectMapPoint(event); }}><iframe title="Delivery location map" src={`https://www.openstreetmap.org/export/embed.html?bbox=${mapCenter.lng - .02}%2C${mapCenter.lat - .012}%2C${mapCenter.lng + .02}%2C${mapCenter.lat + .012}&layer=mapnik`} /><span className="map-pin" style={{ left: `${pinLeft}%`, top: `${pinTop}%` }}><MapPin size={30} fill="currentColor" /></span><div className="map-picker-hint">Tap or drag to move pin</div><div className="map-picker-action"><MapPinned size={17} /> Pin: {coords.lat.toFixed(4)}, {coords.lng.toFixed(4)}<button type="button" onClick={useMyLocation}><Crosshair size={16} /> Use my location</button></div></div><div className="form-row"><div className="form-field"><label>Name</label><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></div><div className="form-field"><label>Mobile number</label><input inputMode="numeric" value={form.mobile} onChange={(e) => setForm({ ...form, mobile: e.target.value.replace(/\D/g, '').slice(0, 10) })} placeholder="10-digit mobile number" /></div></div><div className="form-row"><div className="form-field"><label>Area / address</label><input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Area, street or locality" required /></div><div className="form-field"><label>City</label><input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} placeholder="City" required /></div></div><div className="form-row"><div className="form-field"><label>House / flat no. <small>(optional)</small></label><input value={form.houseNo} onChange={(e) => setForm({ ...form, houseNo: e.target.value })} /></div><div className="form-field"><label>Floor <small>(optional)</small></label><input inputMode="numeric" value={form.floor} onChange={(e) => setForm({ ...form, floor: e.target.value.replace(/\D/g, '') })} /></div></div><div className="form-field"><label>Landmark <small>(optional)</small></label><input value={form.landmark} onChange={(e) => setForm({ ...form, landmark: e.target.value })} placeholder="Nearby landmark" /></div><button className="primary-button save-address-btn" disabled={busy}>{busy ? 'Saving…' : 'Save delivery location'}</button></form>;
}
